// This is a program used to print undocumented constants

#include <Windows.h>
#include <iostream>

#define PRINT_VAL(val) std::cout << #val ": " << val << std::endl

int main ()
{
	PRINT_VAL (LANG_SYSTEM_DEFAULT);
	PRINT_VAL (LANG_USER_DEFAULT);
	PRINT_VAL (LANG_NEUTRAL);
	PRINT_VAL (SUBLANG_NEUTRAL);
	PRINT_VAL (SUBLANG_DEFAULT);
	PRINT_VAL (SUBLANG_SYS_DEFAULT);
	PRINT_VAL (SUBLANG_CUSTOM_DEFAULT);
	PRINT_VAL (SUBLANG_CUSTOM_UNSPECIFIED);
	PRINT_VAL (SUBLANG_UI_CUSTOM_DEFAULT);
	PRINT_VAL (MEMORY_ALLOCATION_ALIGNMENT);
	PRINT_VAL (KF_ALTDOWN);
	PRINT_VAL (KF_DLGMODE);
	PRINT_VAL (KF_EXTENDED);
	PRINT_VAL (KF_MENUMODE);
	PRINT_VAL (KF_REPEAT);
	PRINT_VAL (KF_UP);

	return 0;
}
